### ISSUE TITLE
--results for next version

### ISSUE THREAD

**Issue by ole-tange** [geopal-solutions/gnu-parallel-wrapper#1]
For next version consider using --results to be able to select the output from the individual jobs.

See R version of the same (under active development - so things may change): 
http://git.savannah.gnu.org/cgit/parallel.git/tree/src/optional/R/load-parallel-results.r?id=74014985fe0d151c7024a9299a2afddfd1b730d1

**Comment by geopal-solutions** [comment]
Thanks for the suggestion we will look to put this in in the next version.

**Comment by geopal-solutions** [comment]
This is in the latest version, closing ticket
